baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'TechDiff but React'
primary: true
siteGroup: e545b169-3745-4818-b798-baaadb7faeda # personal
sortOrder: 1
