isPublic: false
name: 'Private Schema'
scope:
  - 'sites.ca348b20-8894-41e8-8cbd-4b61bda22ba5:read' # TechDiff but React
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
